spin_manifest_version = 2

[application]
authors = ["sarem"]
name = "Binance Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://sequencer:8877/post_report"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "binance"

[[trigger.oracle.data_feeds]]
data = '{"symbol":"BTCUSDT"}'
id = "31"

[[trigger.oracle.data_feeds]]
data = '{"symbol":"ETHUSDT"}'
id = "47"

[[trigger.oracle.data_feeds]]
data = '{"symbol":"EURUSDT"}'
id = "253"

[component.binance]
source = "target/wasm32-wasi/release/binance_oracle.wasm"
allowed_outbound_hosts = [
    "https://api.binance.com"
]

[component.binance.build]
command = "cargo build --target wasm32-wasi --release"